<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <DefineConstants>FABLE_COMPILER</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Api.fs" />
    <Compile Include="App.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="Fable.Core" />
    <PackageReference Include="Fable.Browser.Dom" />
    <PackageReference Include="Fable.SimpleHttp" />
    <PackageReference Include="Feliz" />
    <PackageReference Include="Thoth.Json" />
  </ItemGroup>

</Project>
